### ISSUE TITLE
find_all_sift 只能找到一个结果

### ISSUE THREAD

**Issue by welder83** [NetEaseGame/aircv#4]
发现imsrc中即使有多个imsch的匹配结果，find_all_sift也只能找到一个结果。

使用OpenCV sample的find_obj.py测试了下，发现sift一次取样后，好像无法同时匹配多个结果。具体见下图：
![image](https://user-images.githubusercontent.com/30541688/31479896-ef72cdae-af4c-11e7-90ec-aa0b75a45fa9.png)

鉴于SIFT对变形物体的匹配比matchTemplate好，有空能否看下，是否有版本让find_all_sift匹配多个结果。

**Comment by welder83** [comment]
使用版本如下：
aircv (1.4.6)
python2.7.13
opencv-contrib-python (3.3.0.10)
opencv-python (3.3.0.10)

**Comment by codeskyblue** [comment]
@welder83 修改下阈值可以匹配更多一点
