### ISSUE TITLE
为什么我的匹配效果很差

### ISSUE THREAD

**Issue by HoGarfield** [NetEaseGame/aircv#7]
我通过pip install aircv 来安装，但是运行起来无论是find_temple还是find_sift，匹配效果都很差，很多匹配率超过0.999的，完全不是那张图

**Comment by codeskyblue** [comment]
你把测试的图片放上来，好看看是什么问题

**Comment by HoGarfield** [comment]
解决了，用find_all_sift来查找，假如匹配度超过30的话就比较准确

2018-06-21 

garfield_ho 



发件人：shengxiang <notifications@github.com>
发送时间：2018-06-21 17:49
主题：Re: [NetEaseGame/aircv] 为什么我的匹配效果很差 (#7)
收件人："NetEaseGame/aircv"<aircv@noreply.github.com>
抄送："garfield_ho"<garfield_ho@qq.com>,"State change"<state_change@noreply.github.com>

你把测试的图片放上来，好看看是什么问题
