### ISSUE TITLE
是否支持透明背景呢？

### ISSUE THREAD

**Issue by jiangwei1995910** [NetEaseGame/aircv#9]
比如这样一个图形“☆” ，无论如何制作查找图形，都会存在背景干扰，而在被查找图像中，背景可能是不确定的

**Comment by codeskyblue** [comment]
opencv3.0 中的模板匹配其实是支持蒙版的，不错的issue

**Comment by jiangwei1995910** [comment]
非常感谢，我在文档里面找到说明了，这里留个链接给后面需要的人[Click Here](https://docs.opencv.org/3.2.0/de/da9/tutorial_template_matching.html)
